---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-app-deployment
  namespace: default
  labels:
    app: birthday-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: birthday-app
      track: stable
  template:
    metadata:
      labels:
        app: birthday-app
        track: stable
    spec:
      containers:
        - name: birthday-app
          image: DOCKER_IMAGE_PATH
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secret/cloud.google.com/firestore.json
          volumeMounts:
            - name: service-account
              mountPath: /var/run/secret/cloud.google.com
          resources:
            requests:
              cpu: 200m
      volumes:
        - name: service-account
          secret:
            secretName: firebase-access-key

---
apiVersion: v1
kind: Service
metadata:
  name: birthday-app-service
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: birthday-app
    track: stable
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: birthday-app-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: birthday-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50